version: "3.8"
services:
  yadreno:
    build:
      context: .
      args:
        REPO_URL: ${REPO_URL}
        REPO_REF: ${REPO_REF}
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - ADMIN_IDS=${ADMIN_IDS}
    volumes:
      - yadreno_db:/app/database
      - yadreno_logs:/app/logs
    # user: "1000:1000"   # опция: принудительно запускать процесс под uid 1000 (по желанию)

  init-perms:
    image: alpine:latest
    command: ["sh", "-c", "mkdir -p /app/logs /app/database && chown -R 1000:1000 /app/logs /app/database && chmod -R u+rwX /app/logs /app/database"]
    volumes:
      - yadreno_db:/app/database
      - yadreno_logs:/app/logs
    restart: "no"

volumes:
  yadreno_db:
  yadreno_logs:
